# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 973b324708fb5a739c3453592b1efbfd58f9788dc4622f72d0197979b74f65a08aa192221574ac11bd297da110a3965940d3fe90a6bad31f176697786ba514c6

test:
  secret_key_base: 33fdfaacc7c0468cca15033fc80eadf5ff96abaf06312c20aff77ce9b48f804b2ec6678260a3d80dbacddae7c3a051cdae97cd4647d08fc8228665896d81f7f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
